apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-launchpad-operator
  namespace: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idp-launchpad
  template:
    metadata:
      labels:
        app: idp-launchpad
    spec:
      serviceAccountName: idp-operator
      containers:
        - name: operator
          image: idp-launchpad-operator:local
          imagePullPolicy: Never