apiVersion: v1
kind: ServiceAccount
metadata:
  name: idp-operator
  namespace: local
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: idp-operator-role
rules:
  - apiGroups: ["idp.adesso.launchpad"]
    resources: ["platforms","databases"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods","services","secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: idp-operator-binding
subjects:
  - kind: ServiceAccount
    name: idp-operator
    namespace: local
roleRef:
  kind: ClusterRole
  name: idp-operator-role
  apiGroup: rbac.authorization.k8s.io